### ISSUE TITLE
Use github pages to host website for free.

### ISSUE THREAD

**Issue by CodingSpecies** [sumitmukharjeeeeee/scroll-animation#2]
As an idea, why don't you make this into a website, using github's domain? 
If so, this is how to do it:

1. Name all your files with `index`. whateverLanguageYouUsed. 

**Example:**
`index.html`
`index.css`
`index.js`

2. Go to setting of the repo, and go to pages.

![image](https://user-images.githubusercontent.com/70807500/131843080-09c7e1e3-4532-4856-9006-9271aa6213ad.png)

3. Set the branch as main, root, and then save, then above, you will get the domain you just made highlighted in green!
![image](https://user-images.githubusercontent.com/70807500/131843230-ee9d94f1-f21d-4227-b392-96adac881823.png)

Thanks

**Comment by sumitmukharjeeeeee** [comment]
On your suggestion I did that just now, please have a look.
Also if you have LinkedIn account or maybe discord we can connect(If you want to) as I think we did many changes on each other's repos.
Anyway all on yours.

**Comment by CodingSpecies** [comment]
@sumitmukharjeeeeee , looks good. I can happily carry on working helping on github.
Thanks.

**Comment by sumitmukharjeeeeee** [comment]
Alrighty.
